version: '3.6'
services:
  radio_mgmt_agent:
    build:
      context: ./server
      network: host
    ports:
      - "28080:80"
    volumes:
      - ./server/src:/agent
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 80 --reload